fragment FileOrDirPopoverFragment on GitTreeOrBlob {
    ...FilePopoverFragment
    ...DirPopoverFragment
}

fragment FilePopoverFragment on GitBlob {
    path
    isDirectory
    languages
    byteSize
    totalLines
    commit {
        abbreviatedOID
        oid
        subject
        canonicalURL
        author {
            date
            person {
                __typename
                displayName
                avatarURL
                name
            }
        }
    }
}

fragment DirPopoverFragment on GitTree {
    path
    isDirectory
    files {
        name
    }
    directories {
        name
    }
    commit {
        abbreviatedOID
        oid
        subject
        canonicalURL
        author {
            date
            person {
                __typename
                displayName
                avatarURL
                name
            }
        }
    }
}

fragment FileOrDirOwnership on OwnershipConnection {
    totalCount
    totalOwners
    nodes {
        owner {
            __typename
        }
    }
}
